spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Sensenebula?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none          # 表已建好，不改表结构
    show-sql: true